services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - nodenginx
      - nodedb
    depends_on:
      - db

  db:
    image: mysql:9.2
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodenginxchallengedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodedb

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    networks:
      - nodenginx
    ports:
      - "8080:80"
    depends_on:
      - app
      - db

networks:
  nodenginx:
    driver: bridge
  nodedb:
    driver: bridge